name: Continuous Integration

on:
    push:
      branches: [master]
    pull_request:
      branches: [master]

jobs:
  build:
    runs-on: [windows-latest]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1

      - name: Build Solution
        run: dotnet build --configuration Release
      
      - name: Create Test Binaries
        working-directory: Lunar.Tests\TestBinaries
        run: ./Build.bat
        
      - name: Run Tests
        run: dotnet test

  deploy:
    runs-on: [windows-latest]
    needs: [build]
    if: github.event_name == 'push'
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
      
      - name: Create Package
        run: dotnet pack Lunar --configuration Release
      
      - uses: actions/setup-dotnet@v1
        with:
          source-url: https://nuget.pkg.github.com/${{github.actor}}
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Publish Package
        run: dotnet nuget push 'Lunar\bin\Release\*.nupkg' --skip-duplicate